# This Dockerfile is used to build an image to be used to run tests and also to build a final binary.
# The image is tagged as "scalemate-accounts:base" and is referred to from the docker-compose.yml and Dockerfile.
FROM golang:alpine AS build-env

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh make

RUN go get -u github.com/golang/dep/cmd/dep && go get -u github.com/rakyll/gotest
RUN go get -u gopkg.in/alecthomas/gometalinter.v2 && gometalinter.v2 --install

# Set up SSH keys for accessing github private repositories (github.com/mennanov/scalemate/shared).
ARG ID_RSA
ARG ID_RSA_PUB
RUN mkdir -p /root/.ssh && chmod 0700 /root/.ssh
RUN echo "${ID_RSA}" > /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa
RUN echo "${ID_RSA_PUB}" > /root/.ssh/id_rsa.pub
RUN eval "$(ssh-agent)" && ssh-add /root/.ssh/id_rsa
RUN ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
