workspace:
  base: /go/src/github.com/mennanov/
  path: scalemate

steps:
  - name: test
    image: l.gcr.io/google/bazel:latest
    commands:
      - bazel --output_user_root=/tmp/bazel-drone-output --bazelrc=drone.bazelrc test --jobs=4 //...:all --test_output=errors --test_verbose_timeout_warnings
    volumes:
      - name: docker
        host:
          path: /var/run/docker.sock
      - name: bazel
        host:
          path: /tmp/bazel-drone-output

kind: pipeline
name: default

services:
  - name: shared-amqp
    image: rabbitmq:3

  - name: scheduler-db
    image: postgres:11
    tmpfs:
      - /var/lib/postgresql/data

  - name: accounts-db
    image: postgres:11
    tmpfs:
      - /var/lib/postgresql/data
